<?php

use Drupal\Core\Entity\EntityTypeManager;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Entity\EntityDisplayRepositoryInterface;

function tcb_auth_server_install() {
  $entityTypeManager = \Drupal::entityTypeManager();
  
  $fieldStorage = FieldStorageConfig::loadByName('taxonomy_term',
    'field_tcb_site_valid_domains');
  $field = FieldConfig::loadByName('taxonomy_term', 'tcb_site',
    'field_tcb_site_valid_domains');
  
  if(empty($field)) {
    
    \Drupal::logger('tcb_auth_server')->notice('Field not empty');
    
    $field = FieldConfig::create([
      'field_storage' => $fieldStorage,
      'bundle' => 'tcb_site',
      'label' => 'Valid Domains',
      'settings' => ['display_summary' => TRUE],
    ]);
    $field->save();
    
    // Assign widget settings for the default form mode.
    entity_get_form_display('taxonomy_term', 'tcb_site', 'default')
      ->setComponent('field_tcb_site_valid_domains', [
        'type' => 'text_textfield',
      ])
    ->save();
    
    entity_get_display('taxonomy_term', 'tcb_site', 'default')
      ->setComponent('field_tcb_site_valid_domains', [
        'label' => 'Valid Domains',
        'type' => 'text_default',
      ])
    ->save();
    
  }
  else {
    
    \Drupal::logger('tcb_auth_server')->notice('Field Empty');
    
  }

}